#!/usr/bin/env python3
"""Emit src/generated/goblin_name_regions.{hpp,cpp} from data/map_name_regions.json.

The MSB MapNameOverride volumes are the GAME's own region-naming logic (point-in-volume
containment, not nearest-anchor distance). Each = a Box/Cylinder shape (center pos + dims +
yaw) in its MSB map's LOCAL frame, with a PlaceName textId. We bake the ones that carry a
textId, keyed by area/gridX/gridZ (from the map name m{AA}_{GX}_{GZ}_00), so the overlay can
name a marker's location by testing its (area, grid, posX, posZ) against that map's volumes —
the same frame as a WorldMapPointParam row. Replaces the fragile nearest-grace heuristic for
tooltip + cluster-pile labels. Composite shapes (no flat dims) are skipped.
"""
import os, json, math

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "data", "map_name_regions.json")
OUT = os.path.join(ROOT, "src", "generated")


def main():
    d = json.load(open(SRC, encoding="utf-8"))
    rows = []
    for mapname, regions in d.items():
        parts = mapname.split("_")  # m12, 02, 00, 00
        if len(parts) < 3 or not parts[0].startswith("m"):
            continue
        try:
            area = int(parts[0][1:]); gx = int(parts[1]); gz = int(parts[2])
        except ValueError:
            continue
        if not (0 <= area <= 255 and 0 <= gx <= 255 and 0 <= gz <= 255):
            continue
        for r in regions:
            if r.get("kind") != "MapNameOverride":
                continue
            tid = r.get("textId")
            if not tid:
                continue
            shape = r.get("shape")
            dims = r.get("dims", {})
            pos = r.get("pos", [0, 0, 0])
            rot = r.get("rot", [0, 0, 0])
            if shape == "Box":
                hw = float(dims.get("Width", 0)) * 0.5
                hd = float(dims.get("Depth", 0)) * 0.5
                rad = 0.0
                sh = 0
            elif shape == "Cylinder":
                rad = float(dims.get("Radius", 0))
                hw = hd = 0.0
                sh = 1
            else:
                continue  # Composite / unknown — skip
            if hw <= 0 and hd <= 0 and rad <= 0:
                continue
            rows.append({
                "area": area, "gx": gx, "gz": gz, "sh": sh,
                "px": float(pos[0]), "pz": float(pos[2]),
                "hw": hw, "hd": hd, "rad": rad,
                "rot": math.radians(float(rot[1])),  # yaw, radians
                "tid": int(tid), "name": r.get("name", ""),
            })
    # Smallest (most specific) first → the runtime returns the first containing volume.
    rows.sort(key=lambda r: (r["area"], r["gx"], r["gz"],
                             (r["hw"] * r["hd"]) if r["sh"] == 0 else (r["rad"] * r["rad"])))

    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "goblin_name_regions.hpp"), "w", encoding="utf-8", newline="\n") as f:
        f.write("#pragma once\n// AUTO-GENERATED by tools/build_name_regions.py — do not edit.\n"
                "#include <cstddef>\n#include <cstdint>\n\nnamespace goblin::generated\n{\n"
                "// One MSB MapNameOverride volume (the game's own region-naming logic). Frame =\n"
                "// the MSB map's LOCAL coords (same as a WorldMapPointParam row's posX/posZ for\n"
                "// area/gridX/gridZ). shape 0=Box (half_w along X, half_d along Z), 1=Cylinder\n"
                "// (radius). rot = yaw (radians) about Y. text_id = PlaceName id.\n"
                "struct NameRegion { uint8_t area, gx, gz, shape; float px, pz, half_w, half_d, radius, rot; int32_t text_id; };\n"
                "extern const NameRegion NAME_REGIONS[];\nextern const size_t NAME_REGION_COUNT;\n}\n")
    with open(os.path.join(OUT, "goblin_name_regions.cpp"), "w", encoding="utf-8", newline="\n") as f:
        f.write('#include "goblin_name_regions.hpp"\n\nnamespace goblin::generated\n{\n')
        f.write("const NameRegion NAME_REGIONS[] = {\n")
        for r in rows:
            f.write("    {%d,%d,%d,%d, %.3ff,%.3ff, %.3ff,%.3ff,%.3ff, %.5ff, %d}, // %s\n" % (
                r["area"], r["gx"], r["gz"], r["sh"], r["px"], r["pz"],
                r["hw"], r["hd"], r["rad"], r["rot"], r["tid"], r["name"].replace("\n", " ")))
        f.write("};\n")
        f.write("const size_t NAME_REGION_COUNT = %d;\n}\n" % len(rows))
    print("[name-regions] %d volumes -> %s" % (len(rows), OUT))


if __name__ == "__main__":
    main()
