#!/usr/bin/env python3
"""Emit src/generated/goblin_region_anchors.{hpp,cpp} from data/map_name_regions.json.

MSB MapName region volumes give authoritative location NAMES (valid PlaceName ids)
with world centers, covering base + DLC + underground — including areas where the
Site-of-Grace anchors have no name (every DLC area-61 grace stores a tab id, not a
PlaceName). The DLL uses the nearest region anchor in a marker's area as a LABEL
fallback when its grace has no name.

Map key is mAREA_gridX_gridZ_xx, so world coord = gridX*256 + pos.x (same tile-local
convention as the marker rows). pos = [x, y, z]; we use x and z.
"""
import json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "data", "map_name_regions.json")
PLACENAME = os.path.join(ROOT, "data", "PlaceName_engus.json")
OUT_CPP = os.path.join(ROOT, "src", "generated", "goblin_region_anchors.cpp")
OUT_HPP = os.path.join(ROOT, "src", "generated", "goblin_region_anchors.hpp")

valid_pn = set(str(k) for k in json.load(open(PLACENAME)))
data = json.load(open(SRC))

rows = []
seen = set()  # (area, textId, qx, qz) dedupe near-identical anchors
for mapname, regions in data.items():
    m = re.match(r"m(\d+)_(\d+)_(\d+)", mapname)
    if not m:
        continue
    area = int(m.group(1)); gx = int(m.group(2)); gz = int(m.group(3))
    rl = regions if isinstance(regions, list) else regions.get("regions", [])
    for r in rl:
        tid = r.get("textId")
        pos = r.get("pos")
        if not tid or str(tid) not in valid_pn or not pos:
            continue
        if pos[0] == 0.0 and pos[2] == 0.0:
            continue                       # placeholder center
        wx = gx * 256.0 + float(pos[0])
        wz = gz * 256.0 + float(pos[2])
        key = (area, int(tid), round(wx / 32), round(wz / 32))
        if key in seen:
            continue
        seen.add(key)
        rows.append((area, wx, wz, int(tid)))

hpp = """// AUTO-GENERATED by tools/build_region_anchors.py — do not edit.
#pragma once
#include <cstddef>
#include <cstdint>

namespace goblin::generated {

// An authoritative named-location anchor from an MSB MapName region volume. Used
// as a cluster LABEL fallback (esp. DLC, where graces carry no PlaceName).
struct RegionAnchor {
    uint8_t  area;
    float    wx;
    float    wz;
    int32_t  placename_id;
};

extern const RegionAnchor REGION_ANCHORS[];
extern const size_t REGION_ANCHOR_COUNT;

} // namespace goblin::generated
"""

body = "".join(
    "    {{{}, {:.3f}f, {:.3f}f, {}}},\n".format(a, wx, wz, p) for (a, wx, wz, p) in rows
)
cpp = (
    "// AUTO-GENERATED by tools/build_region_anchors.py — do not edit.\n"
    '#include "goblin_region_anchors.hpp"\n\n'
    "namespace goblin::generated {\n\n"
    "const RegionAnchor REGION_ANCHORS[] = {\n"
    + body
    + "};\n\n"
    "const size_t REGION_ANCHOR_COUNT = sizeof(REGION_ANCHORS) / sizeof(REGION_ANCHORS[0]);\n\n"
    "} // namespace goblin::generated\n"
)

open(OUT_HPP, "w").write(hpp)
open(OUT_CPP, "w").write(cpp)
print("wrote {} region anchors -> {}".format(len(rows), OUT_CPP))
