#!/usr/bin/env python3
"""Emit goblin_tile_tabs.{hpp,cpp} from data/tile_region_map.json.

Maps a player's MapId TILE (area, gridX, gridZ) -> map sub-page tabId. Used by the
cluster planner for UNDERGROUND distance-adaptive: underground the player's local
float is leaf-block-local garbage and the marker param gridXNo is coarse (1/2), so
neither Euclidean nor tile distance separates the sub-regions. The MapId tile IS
reliable, and tile_region_map.json keys (m{area}_{gx}_{gz}) carry the authoritative
tabId — so player tile -> tabId, compared against each pile's grace tabId, gives a
"your sub-page = detail, others = clustered" gradient with no RE.

Only NON-overworld tiles are emitted (areas 60/61 use the 256 Euclidean frame and
never need this lookup). Pure JSON -> C++, runs on Linux (no Oodle/regulation).
"""
import json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "data", "tile_region_map.json")
# Canonical copy only (like build_grace_anchors.py). The tile->tab data is profile-
# independent (same game tiling for every bake), so generate_data.py mirrors this
# committed canonical into a non-default profile dir (e.g. generated_vanilla).
OUT_DIRS = [os.path.join(ROOT, "src", "generated")]

KEY = re.compile(r"^m(\d+)_(\d+)_(\d+)$")

def main():
    d = json.load(open(SRC))
    rows = []
    for k, v in d.items():
        m = KEY.match(k)
        if not m:
            continue
        area, gx, gz = (int(x) for x in m.groups())
        tab = v.get("tabId")
        if tab is None:
            continue
        if area in (60, 61):          # overworld uses the Euclidean frame
            continue
        if not (0 <= area <= 255 and 0 <= gx <= 255 and 0 <= gz <= 255):
            continue
        rows.append((area, gx, gz, int(tab)))
    rows.sort()

    hpp = """// AUTO-GENERATED by tools/build_tile_tabs.py — do not edit.
#pragma once
#include <cstddef>
#include <cstdint>

namespace goblin::generated {

// Player MapId TILE -> map sub-page (tabId). NON-overworld tiles only (areas 60/61
// use the Euclidean distance frame). Lets the cluster planner know which underground
// sub-region (Ainsel 12000 / Nokron+Siofra+Mohgwyn 12001 / Deeproot 12002 / DLC
// 6800.. ) the player is in, from the reliable MapId, when local coords break.
struct TileTab { uint8_t area; uint8_t gx; uint8_t gz; int32_t tab; };

extern const TileTab TILE_TABS[];
extern const size_t   TILE_TAB_COUNT;

} // namespace goblin::generated
"""

    body = "\n".join(
        f"    {{ {a}, {gx}, {gz}, {tab} }}," for (a, gx, gz, tab) in rows)
    cpp = f"""// AUTO-GENERATED by tools/build_tile_tabs.py — do not edit.
#include "goblin_tile_tabs.hpp"

namespace goblin::generated {{

const TileTab TILE_TABS[] = {{
{body}
}};
const size_t TILE_TAB_COUNT = {len(rows)};

}} // namespace goblin::generated
"""
    for od in OUT_DIRS:
        os.makedirs(od, exist_ok=True)
        open(os.path.join(od, "goblin_tile_tabs.hpp"), "w").write(hpp)
        open(os.path.join(od, "goblin_tile_tabs.cpp"), "w").write(cpp)
    print(f"wrote {len(rows)} tile->tab entries to {len(OUT_DIRS)} dirs")

if __name__ == "__main__":
    main()
