#!/usr/bin/env python3
"""Emit src/generated/goblin_grace_anchors.{hpp,cpp} from data/grace_position_index.json.

Each grace is an authoritative named-location ANCHOR (from BonfireWarpParam): its
area + world position + region PlaceName id. The DLL assigns every map marker to
its nearest grace in the same (pre-projection) area to form location clusters,
replacing the incomplete textId-based location lookup.

World coord = gridX*256 + x  (same tile-local convention as WORLD_MAP_POINT_PARAM_ST
posX/posZ used in goblin_inject.cpp).
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "data", "grace_position_index.json")
PLACENAME = os.path.join(ROOT, "data", "PlaceName_engus.json")
OUT_CPP = os.path.join(ROOT, "src", "generated", "goblin_grace_anchors.cpp")
OUT_HPP = os.path.join(ROOT, "src", "generated", "goblin_grace_anchors.hpp")

# Valid PlaceName ids (so a cluster label never points at a non-existent string,
# which the game renders as "?PlaceName?"). Many underground/DLC graces carry a
# map TAB id (6800+) in subCategoryId, not a real PlaceName — drop those to 0.
valid_pn = set(str(k) for k in json.load(open(PLACENAME)))

graces = json.load(open(SRC))
rows = []
dropped_pn = 0
for g in graces:
    area = int(g["areaNo"])
    wx = float(g["gridX"]) * 256.0 + float(g["x"])
    wz = float(g["gridZ"]) * 256.0 + float(g["z"])
    pname = int(g.get("subCategoryId") or 0)   # region PlaceName id; 0 = no label
    if pname and str(pname) not in valid_pn:
        pname = 0                              # not a real PlaceName → count-only label
        dropped_pn += 1
    rows.append((area, wx, wz, pname))
print("dropped {} invalid PlaceName labels (-> count-only)".format(dropped_pn))

hpp = """// AUTO-GENERATED by tools/build_grace_anchors.py — do not edit.
#pragma once
#include <cstddef>
#include <cstdint>

namespace goblin::generated {

// An authoritative named-location anchor (a Site of Grace from BonfireWarpParam).
// wx/wz are world coords (gridX*256 + local). placename_id = region PlaceName id
// that renders as the cluster label (0 = no name → count-only label).
struct GraceAnchor {
    uint8_t  area;
    float    wx;
    float    wz;
    int32_t  placename_id;
};

extern const GraceAnchor GRACE_ANCHORS[];
extern const size_t GRACE_ANCHOR_COUNT;

} // namespace goblin::generated
"""

body = "".join(
    "    {{{}, {:.3f}f, {:.3f}f, {}}},\n".format(a, wx, wz, p) for (a, wx, wz, p) in rows
)
cpp = (
    "// AUTO-GENERATED by tools/build_grace_anchors.py — do not edit.\n"
    '#include "goblin_grace_anchors.hpp"\n\n'
    "namespace goblin::generated {\n\n"
    "const GraceAnchor GRACE_ANCHORS[] = {\n"
    + body
    + "};\n\n"
    "const size_t GRACE_ANCHOR_COUNT = sizeof(GRACE_ANCHORS) / sizeof(GRACE_ANCHORS[0]);\n\n"
    "} // namespace goblin::generated\n"
)

open(OUT_HPP, "w").write(hpp)
open(OUT_CPP, "w").write(cpp)
print("wrote {} graces -> {}".format(len(rows), OUT_CPP))
