#!/usr/bin/env python3
"""Emit src/generated/goblin_major_regions.{hpp,cpp} from data/WorldMapPlaceNameParam.json.

The 10 WorldMapPlaceNameParam rows are the game's COARSEST map labels (Limgrave,
Liurnia, Altus, Caelid, Mountaintops, Ainsel/Siofra/Deeproot, Realm of Shadow). They
live in the region-DISCOVERY-banner FMG bank, NOT the map-point-label PlaceName bank —
so their textIds can't be used as a cluster textId1 directly (they render as raw
numbers). Instead we bake the NAME STRING here and inject it into our own PlaceName
bank at a FRESH id (label_id), the same way cluster-count strings are injected.

The DLL uses the nearest anchor in a pile's area as the LAST-RESORT cluster label,
after grace name -> nearest-named grace -> nearest MSB region (188) all miss.

Profile-independent; generate_data.py mirrors the canonical pair into non-default
bakes. World coord = gridX*256 + posX. label_id base 952020000 (clear of cluster
counts 952000000.. and catnames 952010000..).
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "data", "WorldMapPlaceNameParam.json")
PLACENAME = os.path.join(ROOT, "data", "PlaceName_engus.json")
OUT_DIRS = [os.path.join(ROOT, "src", "generated")]
LABEL_BASE = 952020000

def cstr(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

def main():
    pn = json.load(open(PLACENAME))
    def name_of(i):
        return pn.get(str(i)) if isinstance(pn, dict) else None
    data = json.load(open(SRC))
    rows = []
    for r in data:
        tid = r.get("textId")
        nm = name_of(tid)
        if not tid or not nm:                 # skip invalid PlaceName (e.g. 1000)
            continue
        area = int(r.get("areaNo", 0))
        gx = int(r.get("gridXNo", 0)); gz = int(r.get("gridZNo", 0))
        wx = gx * 256.0 + float(r.get("posX", 0.0))
        wz = gz * 256.0 + float(r.get("posZ", 0.0))
        rows.append((area, wx, wz, nm))
    rows.sort()
    rows = [(a, wx, wz, LABEL_BASE + i, nm) for i, (a, wx, wz, nm) in enumerate(rows)]
    # Manual fix: some WorldMapPlaceNameParam rows carry a LEGACY/local area (e.g. Limgrave
    # = area 10 with m10-local coords) → draw_region_labels (which doesn't re-project) sends
    # them off-screen. Override with the correct OVERWORLD (area 60) world coord = the
    # centroid of that region's MapNameOverride volumes (data/map_name_regions.json).
    OVERRIDE = {"Limgrave": (60, 10731.0, 9553.0)}
    rows = [(OVERRIDE[nm][0], OVERRIDE[nm][1], OVERRIDE[nm][2], lid, nm) if nm in OVERRIDE
            else (a, wx, wz, lid, nm) for (a, wx, wz, lid, nm) in rows]

    hpp = """// AUTO-GENERATED by tools/build_major_regions.py — do not edit.
#pragma once
#include <cstddef>
#include <cstdint>

namespace goblin::generated {

// Coarsest map-region anchors (WorldMapPlaceNameParam): one point per major region.
// LAST-RESORT cluster label. label_id = a FRESH PlaceName id whose string `name` is
// injected into our PlaceName bank by setup_messages (the source textId is in the
// region-banner FMG bank, unusable as a map-point label, so we re-home the string).
struct MajorRegionAnchor { uint8_t area; float wx; float wz; int32_t label_id; const char *name; };

extern const MajorRegionAnchor MAJOR_REGION_ANCHORS[];
extern const size_t            MAJOR_REGION_ANCHOR_COUNT;

} // namespace goblin::generated
"""
    body = "\n".join(
        f"    {{ {a}, {wx:.4f}f, {wz:.4f}f, {lid}, {cstr(nm)} }}," for (a, wx, wz, lid, nm) in rows)
    cpp = f"""// AUTO-GENERATED by tools/build_major_regions.py — do not edit.
#include "goblin_major_regions.hpp"

namespace goblin::generated {{

const MajorRegionAnchor MAJOR_REGION_ANCHORS[] = {{
{body}
}};
const size_t MAJOR_REGION_ANCHOR_COUNT = {len(rows)};

}} // namespace goblin::generated
"""
    for od in OUT_DIRS:
        os.makedirs(od, exist_ok=True)
        open(os.path.join(od, "goblin_major_regions.hpp"), "w").write(hpp)
        open(os.path.join(od, "goblin_major_regions.cpp"), "w").write(cpp)
    print(f"wrote {len(rows)} major-region anchors (label ids {LABEL_BASE}..{LABEL_BASE+len(rows)-1})")

if __name__ == "__main__":
    main()
