#!/usr/bin/env python3
"""Generate per-map coverage docs: mod marker counts vs MapGenie counts, drift-flagged.

Writes docs/coverage_base.md (area 60) and docs/coverage_dlc.md (area 61). For
each type it shows MapGenie's count, the mod's count, and a status flag — the
important one being ⚠️ when mod < MapGenie (a real gap / missing markers). mod >
MapGenie is expected (ERR adds content) and only noted.

MapGenie numbers are hand-entered from the site's category panels (Locations so
far); fill MAPGENIE_ITEMS as you gather the rest. Mod numbers are computed from
the baked data with the same projection the DLL uses.

Usage:  tools/coverage_vs_mapgenie.py
"""
import os
import re
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEN = os.path.join(ROOT, "src", "generated")
DOCS = os.path.join(ROOT, "docs")

# ── MapGenie "Locations" counts (from the site's panels) ──────────────────────
MAPGENIE_LOCATIONS = {
    60: {  # The Lands Between
        "Site of Grace": 309, "Stake of Marika": 97, "Spiritspring Jump": 38,
        "Imp Seal Statue": 38, "Divine Tower": 6, "Dragon Shrine": 2,
        "Dungeon": 53, "Elevator": 24, "Evergaol": 11, "Hidden Passage": 40,
        "Landmark": 131, "Legacy Dungeon": 7, "Martyr Effigy": 156,
        "Minor Erdtree": 11, "Portal": 36, "Smithing Table": 1,
        "Wandering Mausoleum": 7,
    },
    61: {  # The Shadow Realm (DLC)
        "Site of Grace": 105, "Stake of Marika": 22, "Spiritspring Jump": 18,
        "Dungeon": 11, "Elevator": 16, "Hidden Passage": 19, "Landmark": 41,
        "Martyr Effigy": 56, "Miquella's Cross": 13, "Portal": 3,
    },
}

# mod Category enum name -> MapGenie Location label (only where they correspond).
# Several mod categories can sum into one MapGenie label.
CAT_TO_MG = {
    "WorldGraces": "Site of Grace",
    "WorldImpStatues": "Imp Seal Statue",
    "WorldStakesOfMarika": "Stake of Marika",
    "WorldSpiritSprings": "Spiritspring Jump",
    "WorldSpiritspringHawks": "Spiritspring Jump",
}

# Macro-groups for the mod-only item section.
GROUPS = ["Equip", "Loot", "Key", "Magic", "World", "Reforged", "Quest"]

# Optional: MapGenie item-category counts (fill as you collect them), keyed by
# area then mod-category enum name. Leave empty -> shown as "?" (to fill).
MAPGENIE_ITEMS = {60: {}, 61: {}}


def parse_legacy_conv():
    txt = open(os.path.join(GEN, "goblin_legacy_conv.hpp")).read()
    rows = []
    for m in re.finditer(
        r"\{\s*(\d+),\s*(\d+),\s*([-\d.]+)f,\s*([-\d.]+)f,\s*"
        r"(\d+),\s*(\d+),\s*(\d+),\s*([-\d.]+)f,\s*([-\d.]+)f\s*\}", txt):
        g = [float(x) if "." in x else int(x) for x in m.groups()]
        rows.append(g)  # [s_area,s_gx,s_px,s_pz,d_area,d_gx,d_gz,d_px,d_pz]
    return rows


CONV = parse_legacy_conv()


def dst_area(area, gx):
    if area in (60, 61):
        return area
    fb = None
    for c in CONV:
        if c[0] != area:
            continue
        if fb is None:
            fb = c[4]
        if c[1] == gx:
            return c[4]
    return fb  # None if unmappable


def mod_counts():
    """Return {area: Counter(category -> n)} using the DLL's projection target."""
    txt = open(os.path.join(GEN, "goblin_map_data.cpp"), errors="replace").read()
    out = {60: Counter(), 61: Counter()}
    for blk in txt.split("// Row ID ")[1:]:
        a = re.search(r"\.areaNo\s*=\s*(\d+)", blk)
        gx = re.search(r"\.gridXNo\s*=\s*(\d+)", blk)
        cat = re.search(r"Category::(\w+)", blk)
        if not (a and cat):
            continue
        da = dst_area(int(a.group(1)), int(gx.group(1)) if gx else 0)
        if da in out:
            out[da][cat.group(1)] += 1
    return out


def group_of(cat):
    for g in GROUPS:
        if cat.startswith(g):
            return g
    return "Other"


def status(mod, mg):
    if mg is None:
        return "—"
    if mod < mg:
        return f"⚠️ DRIFT mod<MG (−{mg - mod})"
    if mod > mg:
        return f"ℹ️ mod>MG (+{mod - mg}, ERR?)"
    return "✅"


def write_doc(area, counts, path, title):
    mg_loc = MAPGENIE_LOCATIONS.get(area, {})
    # mod count summed per MapGenie label
    mg_label_mod = Counter()
    for cat, n in counts.items():
        if cat in CAT_TO_MG:
            mg_label_mod[CAT_TO_MG[cat]] += n

    L = [f"# {title} — mod vs MapGenie coverage",
         "",
         "_Generated by tools/coverage_vs_mapgenie.py. ⚠️ = mod has FEWER than "
         "MapGenie (likely a gap). ℹ️ = mod has more (ERR adds content)._",
         "",
         "## Locations (MapGenie taxonomy)",
         "",
         "| MapGenie Location | MapGenie | Mod | Status |",
         "|---|--:|--:|---|"]
    for label in sorted(mg_loc):
        mg = mg_loc[label]
        mod = mg_label_mod.get(label, 0)
        wired = label in CAT_TO_MG.values()
        st = status(mod, mg) if wired else f"❌ NOT WIRED (need {mg})"
        L.append(f"| {label} | {mg} | {mod if wired else 0} | {st} |")

    # mod-only categories (no MapGenie Locations equivalent), grouped
    L += ["", "## Mod item/feature categories (MapGenie item counts TODO)", "",
          "| Category | Mod | MapGenie | Status |", "|---|--:|--:|---|"]
    mapped = set(CAT_TO_MG)
    for g in GROUPS + ["Other"]:
        cats = sorted([c for c in counts if group_of(c) == g and c not in mapped],
                      key=lambda c: -counts[c])
        for c in cats:
            mg = MAPGENIE_ITEMS.get(area, {}).get(c)
            L.append(f"| {c} | {counts[c]} | {mg if mg is not None else '?'} | "
                     f"{status(counts[c], mg)} |")

    total_mod = sum(counts.values())
    drifts = sum(1 for label in mg_loc
                 if label in CAT_TO_MG.values()
                 and mg_label_mod.get(label, 0) < mg_loc[label])
    notwired = sum(1 for label in mg_loc if label not in CAT_TO_MG.values())
    L += ["", "## Summary", "",
          f"- mod markers on this map: **{total_mod}**",
          f"- MapGenie Location types NOT wired: **{notwired}**",
          f"- wired Location types where mod < MapGenie (⚠️): **{drifts}**", ""]
    open(path, "w").write("\n".join(L))
    print(f"wrote {os.path.relpath(path, ROOT)}  (mod markers {total_mod}, "
          f"{notwired} unwired locations, {drifts} drift)")


def main():
    os.makedirs(DOCS, exist_ok=True)
    counts = mod_counts()
    write_doc(60, counts[60], os.path.join(DOCS, "coverage_base.md"),
              "The Lands Between (base)")
    write_doc(61, counts[61], os.path.join(DOCS, "coverage_dlc.md"),
              "The Shadow Realm (DLC)")


if __name__ == "__main__":
    main()
