"""Generate src/generated/goblin_model_aliases.{hpp,cpp} — gather-asset model aliases.

ERR substitutes some base-game gather assets with their DLC-era equivalents at runtime
(e.g. AEG099_753 "Sacramental Burgeon" instantiates as AEG463_860). GeomFlagSaveDataManager
then records the pick under the ACTUAL model's hash, so collected-tracking that matches by
the MSB-name prefix (AEG099_753) misses the GEOF entry and the icon stays visible while the
tile is unloaded.

Alias rule: models sharing the same primary goodsId are the same physical node. Group by
goodsId across aeg099_item_mapping.json + aeg463_item_mapping.json, skip goods 17000 (the
160-model junk-drop group; those nodes are never markered).

Usage: py generate_model_aliases.py
"""
import os, sys, io, json
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))
D = os.path.join(HERE, "..", "data")
GEN = os.path.join(HERE, "..", "src", "generated")

def goods_of(e):
    if e.get("items"):
        return e["items"][0].get("goodsId")
    return e.get("goodsId")

def model_id(model):
    # "AEG099_753" -> 10099753 (matches GEOF model hash / prefix_from_model_id)
    grp, num = model[3:6], model[7:10]
    return 10000000 + int(grp) * 1000 + int(num)

a99 = json.load(open(os.path.join(D, "aeg099_item_mapping.json"), encoding="utf-8"))
a463 = json.load(open(os.path.join(D, "aeg463_item_mapping.json"), encoding="utf-8"))
from collections import defaultdict
groups = defaultdict(set)
onetime_goods = set()
for e in a99 + a463:
    g = goods_of(e)
    if not g or g == 17000:
        continue
    groups[g].add(e["model"])
    # collected-tracking only covers one-time gather nodes (material-node markers);
    # alias groups without any such model are dead weight (e.g. golden-rune piles)
    if e.get("isEnableRepick") and e.get("isHiddenOnRepick"):
        onetime_goods.add(g)
groups = {g: ms for g, ms in groups.items() if g in onetime_goods}

pairs = []
for g, models in sorted(groups.items()):
    if len(models) < 2:
        continue
    ms = sorted(models)
    for a in ms:
        for b in ms:
            if a != b:
                pairs.append((model_id(a), model_id(b), a, b, g))
pairs.sort()

with open(os.path.join(GEN, "goblin_model_aliases.hpp"), "w", encoding="utf-8") as f:
    f.write("""#pragma once

#include <cstddef>
#include <cstdint>

namespace goblin::generated
{

// Gather-asset model aliases (same physical node, different model ids). ERR substitutes
// some base assets with DLC-era models at runtime; GEOF save entries then carry the
// substituted model's hash. When GEOF's model prefix has no marker rows on a tile, try
// its aliases. Built from shared goodsId across aeg099/aeg463 item mappings.
struct ModelAlias
{
    uint32_t model_id;  // model id as found in a GEOF entry (e.g. 10463860 = AEG463_860)
    uint32_t alias_id;  // equivalent model id used by marker rows (e.g. 10099753)
};

extern const ModelAlias MODEL_ALIASES[];  // sorted by model_id
extern const size_t MODEL_ALIAS_COUNT;

} // namespace goblin::generated
""")
with open(os.path.join(GEN, "goblin_model_aliases.cpp"), "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED FILE - DO NOT EDIT\n")
    f.write("// Generated by tools/generate_model_aliases.py from aeg099/aeg463 item mappings\n\n")
    f.write('#include "goblin_model_aliases.hpp"\n\n')
    f.write("namespace goblin::generated\n{\n\n")
    f.write(f"const size_t MODEL_ALIAS_COUNT = {len(pairs)};\n\n")
    f.write("const ModelAlias MODEL_ALIASES[] = {\n")
    for mid, aid, a, b, g in pairs:
        f.write(f"    {{{mid}u, {aid}u}},  // {a} -> {b} (goods {g})\n")
    if not pairs:
        f.write("    {0u, 0u},\n")
    f.write("};\n\n} // namespace goblin::generated\n")
print(f"wrote {len(pairs)} alias pairs -> src/generated/goblin_model_aliases.cpp")
for mid, aid, a, b, g in pairs[:6]:
    print(f"   {a} -> {b} (goods {g})")
