#!/usr/bin/env python3
"""Category descriptor — single source of truth for marker-category metadata.

Tier 1 of docs/plans/category_descriptor_plan.md. The authoritative table is
data/categories.json (ordered EXACTLY like the Category enum). This script
generates src/generated/goblin_categories.gen.hpp (the CATEGORY_META array the
name + section lookups read), so those two hand-written C++ switches become data.

Bootstrap: if data/categories.json is missing, it is first EXTRACTED from the
current C++ (the enum order + the category_name / section_of switches) so the
migration starts byte-faithful; thereafter categories.json is the edited source.

Usage: tools/generate_categories.py            # extract-if-missing, then generate
       tools/generate_categories.py --extract  # force re-extract from C++ (bootstrap)
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENUM_HPP = ROOT / "src" / "generated" / "goblin_map_data.hpp"
NAMES_CPP = ROOT / "src" / "goblin_markers.cpp"
SECT_CPP = ROOT / "src" / "goblin_section_visibility.cpp"
LAND_CPP = ROOT / "src" / "worldmap" / "map_entry_layer.cpp"
JSON = ROOT / "data" / "categories.json"
GEN_HPP = ROOT / "src" / "generated" / "goblin_categories.gen.hpp"
GEN_INC = ROOT / "src" / "generated" / "goblin_categories_enum.gen.inc"


def parse_enum_order():
    """Ordered list of Category enumerator names, from the enum block."""
    txt = ENUM_HPP.read_text(encoding="utf-8")
    m = re.search(r"enum class Category\s*:[^\{]*\{(.*?)\};", txt, re.S)
    if not m:
        sys.exit("could not find `enum class Category` block")
    order = []
    for raw in m.group(1).splitlines():
        line = raw.split("//", 1)[0].strip()  # drop trailing comments
        if not line:
            continue
        for tok in line.split(","):
            tok = tok.strip()
            if re.fullmatch(r"[A-Za-z_]\w*", tok):
                order.append(tok)
    return order


def parse_names():
    """{enum -> display name} from category_name()'s `case C::X: return "...";`."""
    txt = NAMES_CPP.read_text(encoding="utf-8")
    return dict(re.findall(r'case C::(\w+):\s*return "([^"]*)";', txt))


def parse_sections():
    """{enum -> Section name} from section_of()'s fall-through case groups."""
    txt = SECT_CPP.read_text(encoding="utf-8")
    m = re.search(r"Section section_of\(Category c\)\s*\{(.*?)\n\}", txt, re.S)
    if not m:
        sys.exit("could not find `section_of` function")
    out, pending = {}, []
    for line in m.group(1).splitlines():
        cm = re.search(r"case Category::(\w+):", line)
        if cm:
            pending.append(cm.group(1))
            continue
        rm = re.search(r"return Section::(\w+);", line)
        if rm:
            for c in pending:
                out[c] = rm.group(1)
            pending = []
    return out


def parse_landmarks():
    """{enum -> [iconId,...]} from landmark_category_for_icon()'s case groups."""
    txt = LAND_CPP.read_text(encoding="utf-8")
    m = re.search(r"int landmark_category_for_icon\(int iconId\)\s*\{(.*?)\n\}", txt, re.S)
    if not m:
        sys.exit("could not find `landmark_category_for_icon` function")
    out, pending = {}, []
    for line in m.group(1).splitlines():
        for cm in re.findall(r"case (\d+):", line):  # several `case N:` may share a line
            pending.append(int(cm))
        rm = re.search(r"Category::(\w+)\)", line)
        if rm:
            out.setdefault(rm.group(1), []).extend(pending)
            pending = []
    return {k: sorted(v) for k, v in out.items()}


def extract_to_json():
    order = parse_enum_order()
    names = parse_names()
    sects = parse_sections()
    land = parse_landmarks()
    missing = [c for c in order if c not in names or c not in sects]
    if missing:
        sys.exit(f"enum categories with no name/section: {missing}")
    rows = []
    for c in order:
        row = {"enum": c, "name": names[c], "section": sects[c]}
        if land.get(c):
            row["landmark_icon_ids"] = land[c]
        rows.append(row)
    JSON.parent.mkdir(parents=True, exist_ok=True)
    JSON.write_text(json.dumps(rows, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"extracted {len(rows)} categories -> {JSON.relative_to(ROOT)}")
    return rows


def cpp_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def generate(rows):
    lines = [
        "#pragma once",
        "// GENERATED by tools/generate_categories.py from data/categories.json — DO NOT EDIT.",
        "// Category metadata (display name + section), indexed by Category enum value. Tier 1 of",
        "// docs/plans/category_descriptor_plan.md — the single source of truth for name + section.",
        "",
        '#include "goblin_map_data.hpp"',
        "",
        "namespace goblin::generated",
        "{",
        "struct CategoryMetaRow { const char *name; const char *section; };",
        "",
        "// One row per Category, in enum order (index == static_cast<int>(Category)).",
        "inline constexpr CategoryMetaRow CATEGORY_META[] = {",
    ]
    width = max(len(cpp_str(r["name"])) for r in rows)
    for r in rows:
        nm = cpp_str(r["name"])
        lines.append(f"    {{{nm:<{width}}, {cpp_str(r['section'])}}},  // {r['enum']}")
    lines += [
        "};",
        "",
        "inline constexpr int CATEGORY_META_COUNT ="
        " static_cast<int>(sizeof(CATEGORY_META) / sizeof(CATEGORY_META[0]));",
        "",
        "// iconId -> landmark Category (int), or -1. Built from each category's",
        "// landmark_icon_ids in data/categories.json; drives build_live_landmarks().",
        "inline int landmark_category_for_icon(int iconId)",
        "{",
        "    switch (iconId)",
        "    {",
    ]
    for r in rows:
        ids = r.get("landmark_icon_ids")
        if not ids:
            continue
        for i in ids:
            lines.append(f"    case {i}:")
        lines[-1] += f" return static_cast<int>(Category::{r['enum']});"
    lines += [
        "    default: return -1;",
        "    }",
        "}",
        "",
    ]

    def flt(x):
        return repr(float(x)) + "f"  # repr keeps a decimal point -> valid float literal

    # Numeric engine-glyph per category (iconId + per-category scale + ABGR tint). Sparse.
    lines += [
        "// Per-category native map glyph (numeric iconId + scale + ABGR tint). From each",
        "// category's `glyph` in data/categories.json. Sparse — absent = baked-only / circle.",
        "struct CategoryGpuIcon { int category; int iconId; float scale; unsigned int tint; };",
        "inline constexpr CategoryGpuIcon CATEGORY_GPU_ICONS[] = {",
        "    {-1, 0, 1.0f, 0u},  // sentinel (never matches a real category; keeps the array non-empty)",
    ]
    for r in rows:
        g = r.get("glyph")
        if not g:
            continue
        t = g.get("tint")
        if t:
            tint_u = (235 << 24) | (t[2] << 16) | (t[1] << 8) | t[0]
            tint = f"{tint_u}u"
            note = f"  // tint rgb({t[0]},{t[1]},{t[2]})"
        else:
            tint, note = "0u", ""
        lines.append(f"    {{static_cast<int>(Category::{r['enum']}), {g['icon_id']}, "
                     f"{flt(g['scale'])}, {tint}}},{note}")
    lines.append("};")
    lines.append("")

    # Name-keyed engine map symbol per category (ERR MENU_MAP_ERR_* / vanilla MENU_MAP_*). Sparse.
    lines += [
        "// Per-category NAME-keyed engine map symbol (+ scale). From each category's `glyph_name`",
        "// in data/categories.json. Sparse — most categories have none.",
        "struct CategoryGpuName { int category; const char *name; float scale; };",
        "inline constexpr CategoryGpuName CATEGORY_GPU_NAMES[] = {",
    ]
    for r in rows:
        g = r.get("glyph_name")
        if not g:
            continue
        lines.append(f"    {{static_cast<int>(Category::{r['enum']}), {cpp_str(g['name'])}, "
                     f"{flt(g['scale'])}}},")
    lines.append("};")

    lines += ["} // namespace goblin::generated", ""]
    GEN_HPP.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {GEN_HPP.relative_to(ROOT)}  ({len(rows)} rows)")

    # Enum body (.inc), #included inside `enum class Category : uint8_t { ... }` in
    # goblin_map_data.hpp. Emitted in the same order as the table (== enum value), so the
    # generated values are identical to the hand-written enum. Comments preserved from json.
    inc = [
        "// GENERATED by tools/generate_categories.py from data/categories.json — DO NOT EDIT.",
        "// Category enumerators, #included inside `enum class Category : uint8_t { ... }`.",
    ]
    for r in rows:
        for c in r.get("enum_pre_comment", []):
            inc.append(f"    // {c}")
        lc = r.get("enum_line_comment")
        inc.append(f"    {r['enum']},{('  // ' + lc) if lc else ''}")
    GEN_INC.write_text("\n".join(inc) + "\n", encoding="utf-8")
    print(f"wrote {GEN_INC.relative_to(ROOT)}  ({len(rows)} enumerators)")


def main():
    # data/categories.json is the SOURCE OF TRUTH (committed). --extract is the historical
    # bootstrap that reconstructs it from the old C++ switches — it only works BEFORE those
    # switches were migrated to the table, so it is not used in normal runs.
    if "--extract" in sys.argv[1:]:
        rows = extract_to_json()
    elif not JSON.exists():
        sys.exit(f"{JSON.relative_to(ROOT)} missing — it is the source of truth; restore it from git "
                 "(the C++ switches it replaced are gone, so --extract can no longer rebuild it).")
    else:
        rows = json.loads(JSON.read_text(encoding="utf-8"))
    generate(rows)


if __name__ == "__main__":
    main()
