#!/usr/bin/env python3
"""
Generate the live runtime C++ tables (NOT the marker bake — that was retired in Phase 2).

Emits:
  - src/generated/goblin_map_data.cpp        (Phase-2 empty no-bake stub; markers come live/disk)
  - src/generated/goblin_category_exceptions.cpp
  - src/generated/goblin_name_aliases_en.cpp
  - src/generated/goblin_legacy_conv.hpp     (dungeon -> overworld coord conversion)

Localization is handled by the DLL at runtime via FMG offset-encoding
(textId = real_id + category_offset), so no text compilation step is needed.
"""

import os
import re
import json
import sys
from collections import defaultdict
from pathlib import Path

# Category mapping: MASSEDIT filename prefix -> Category enum
CATEGORY_MAP = {
    "Equipment - Armaments": "EquipArmaments",
    "Equipment - Armour": "EquipArmour",
    "Equipment - Ashes of War": "EquipAshesOfWar",
    "Equipment - Spirits": "EquipSpirits",
    "Equipment - Talismans": "EquipTalismans",
    "Key - Celestial Dew": "KeyCelestialDew",
    "Key - Cookbooks": "KeyCookbooks",
    "Key - Crystal Tears": "KeyCrystalTears",
    "Key - Great Runes": "KeyGreatRunes",
    "Key - Imbued Sword Keys": "KeyImbuedSwordKeys",
    "Key - Larval Tears": "KeyLarvalTears",
    "Key - Lost Ashes": "KeyLostAshes",
    "Key - Pots n Perfumes": "KeyPotsNPerfumes",
    "Key - Scadutree Fragments": "KeyScadutreeFragments",
    "Key - Seeds Tears Ashes": "KeySeedsTears",
    "Key - Whetblades": "KeyWhetblades",
    "Loot - Ammo": "LootAmmo",
    "Loot - Bell-Bearings": "LootBellBearings",
    "Loot - Consumables": "LootConsumables",
    "Loot - Crafting Materials": "LootCraftingMaterials",
    "Loot - Gestures": "LootGestures",
    "Loot - Gloveworts": "LootGloveworts",
    "Loot - Golden Runes": "LootGoldenRunes",
    "Loot - Golden Runes (Low)": "LootGoldenRunesLow",
    "Loot - Great Gloveworts": "LootGreatGloveworts",
    "Loot - Greases": "LootGreases",
    "Loot - Material Nodes": "LootMaterialNodes",
    "Loot - Merchant Bell-Bearings": "LootMerchantBellBearings",
    "Loot - MP-Fingers": "LootMPFingers",
    "Loot - Prattling Pates": "LootPrattlingPates",
    "Loot - Rada Fruit": "LootRadaFruit",
    "Loot - Reusables": "LootReusables",
    "Loot - Smithing Stones": "LootSmithingStones",
    "Loot - Smithing Stones (Low)": "LootSmithingStonesLow",
    "Loot - Smithing Stones (Rare)": "LootSmithingStonesRare",
    "Loot - Stat Boosts": "LootStatBoosts",
    "Loot - Stonesword Keys": "LootStoneswordKeys",
    "Loot - Throwables": "LootThrowables",
    "Loot - Rune Arcs": "LootRuneArcs",
    "Loot - Dragon Hearts": "LootDragonHearts",
    "Loot - Utilities": "LootUtilities",
    "Magic - Incantations": "MagicIncantations",
    "Magic - Memory Stones": "MagicMemoryStones",
    "Magic - Prayerbooks": "MagicPrayerbooks",
    "Magic - Sorceries": "MagicSorceries",
    "Quest - Deathroot": "QuestDeathroot",
    "Quest - Progression": "QuestProgression",
    "Quest - Seedbed Curses": "QuestSeedbedCurses",
    "Reforged - Ember Pieces": "ReforgedEmberPieces",
    "Reforged - Fortunes": "ReforgedFortunes",
    "Reforged - Items": "ReforgedItemsAndChanges",
    "Reforged - Rune Pieces": "ReforgedRunePieces",
    "Reforged - Sealed Curios": "ReforgedItemsAndChanges",
    "World - Bosses": "WorldBosses",
    "World - Graces": "WorldGraces",
    "World - Hostile NPC": "WorldHostileNPC",
    "World - Quest NPC": "WorldQuestNPC",
    "World - Imp Statues": "WorldImpStatues",
    "World - Maps": "WorldMaps",
    "World - Paintings": "WorldPaintings",
    "World - Spirit Springs": "WorldSpiritSprings",
    "World - Spiritspring Hawks": "WorldSpiritspringHawks",
    "World - Stakes of Marika": "WorldStakesOfMarika",
    "World - Summoning Pools": "WorldSummoningPools",
    "World - Kindling Spirits": "WorldKindlingSpirits",
    "World - Seal Puzzles": "WorldInteractables",
    "World - Hero's Tomb Statues": "WorldInteractables",
}

# Phase-2 no-bake stub written to the COMPILED goblin_map_data.cpp. The static marker bake is
# retired — every marker comes from live mod files / game memory at runtime — so the compiled
# table is empty. A 0-length array is ill-formed, so a 1-elem zero dummy is emitted and never
# read (every consumer iterates `i < MAP_ENTRY_COUNT` == 0). The Category enum + MapEntry types
# stay in goblin_map_data.hpp (they drive the overlay layers/buckets).
_MAP_DATA_STUB = (
    "// AUTO-GENERATED FILE - DO NOT EDIT\n"
    "// Generated by tools/generate_data.py — PHASE-2 NO-BAKE STUB (the static marker bake is\n"
    "// retired; every marker comes from live mod files / game memory at runtime). The full\n"
    "// MapEntry table is no longer materialised anywhere — the last consumers of it\n"
    "// (generate_geof_models, generate_location_overrides) were retired in the Phase-2 cleanup.\n\n"
    '#include "goblin_map_data.hpp"\n\n'
    "namespace goblin::generated\n{\n\n"
    "const size_t MAP_ENTRY_COUNT = 0;\n\n"
    "// Never read (COUNT == 0 gates every consumer loop); a 0-length array is ill-formed.\n"
    "const MapEntry MAP_ENTRIES[1] = {};\n\n"
    "} // namespace goblin::generated\n"
)


def generate_map_data_cpp(output_path):
    """Phase 2 (no-bake): the COMPILED goblin_map_data.cpp is an EMPTY STUB. The full MapEntry
    table used to be emitted to an uncompiled intermediate for two downstream generators, but both
    (generate_geof_models, generate_location_overrides) were retired — the gather model now comes
    live from the MSB part modelIndex and the location names from the runtime resolver — so nothing
    text-parses the table any more. We just write the constant stub."""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(_MAP_DATA_STUB)
    print(f"Generated {output_path} (Phase-2 empty no-bake stub)")


# Phase-3: item categories the mod assigns by a deliberate id-list/name rule that ER's own
# taxonomy (goodsType, sortGroupId) cannot express — they STAY as a curated per-item table.
# Everything else is classified live from (goodsType, sortGroupId) in the DLL (drift-free).
# Validated to reproduce the old ITEM_ICONS category column exactly (_validate_taxonomy_map.py).
CATEGORY_EXCEPTION_CATS = {
    "Loot - Golden Runes (Low)",
    "Loot - Smithing Stones (Low)", "Loot - Smithing Stones (Rare)",
    "Loot - Great Gloveworts",
    "Loot - Rune Arcs", "Loot - Prattling Pates", "Loot - MP-Fingers", "Loot - Rada Fruit",
    "Key - Celestial Dew", "Key - Imbued Sword Keys", "Loot - Stonesword Keys",
    "Quest - Deathroot", "Quest - Seedbed Curses",
    "Key - Whetblades", "Key - Larval Tears", "Key - Lost Ashes", "Loot - Dragon Hearts",
    "Key - Scadutree Fragments", "Key - Seeds Tears Ashes",
    "Magic - Memory Stones", "Magic - Prayerbooks",
    "Quest - Progression",
    "Reforged - Items", "Reforged - Fortunes", "Reforged - Sealed Curios",
}


def generate_category_exceptions_cpp(output_path):
    """Generate goblin_category_exceptions.cpp: raw goods id -> Category, for the
    curated splits/grab-bags ER's own taxonomy can't express (Phase-3). Source =
    item_icon_table.json (the LOOT_CATEGORIES classifier); only goods whose category
    is in CATEGORY_EXCEPTION_CATS are emitted. Sorted by id for binary search."""
    import config
    p = config.DATA_DIR / 'item_icon_table.json'
    rows = {}  # goods_id(int) -> Category enum name
    if p.exists():
        with open(p, encoding='utf-8') as f:
            raw = json.load(f)
        for k, v in raw.items():
            key = int(k)
            if key < 500000000:
                continue  # exceptions are goods-only (non-goods classify by key range)
            cat_name = v[1]
            if cat_name not in CATEGORY_EXCEPTION_CATS:
                continue
            enum = CATEGORY_MAP.get(cat_name)
            if enum:
                rows[key - 500000000] = enum

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED FILE - DO NOT EDIT\n")
        f.write("// Generated by tools/generate_data.py from item_icon_table.json\n\n")
        f.write('#include "goblin_category_exceptions.hpp"\n\n')
        f.write("namespace goblin::generated\n{\n\n")
        f.write(f"const size_t CATEGORY_EXCEPTION_COUNT = {len(rows)};\n\n")
        f.write("const CategoryException CATEGORY_EXCEPTIONS[] = {\n")
        for gid in sorted(rows.keys()):
            f.write(f"    {{{gid}, Category::{rows[gid]}}},\n")
        f.write("};\n\n")
        f.write("} // namespace goblin::generated\n")

    print(f"Generated {output_path} with {len(rows)} category exceptions")


def _wlit(s):
    """C++ wide-string literal with every non-ASCII unit as \\uXXXX (encoding-safe)."""
    units = s.encode("utf-16-le")
    out = []
    for i in range(0, len(units), 2):
        cu = units[i] | (units[i + 1] << 8)
        if 0x20 <= cu < 0x7f and chr(cu) not in '"\\':
            out.append(chr(cu))
        else:
            out.append("\\u%04x" % cu)
    return 'L"' + "".join(out) + '"'




# Offset-encoded name-id scheme, identical to encode_live_item() in
# goblin_inject.cpp and the markers' baked textId1 (so the alias keys line up
# with Marker::name_id at runtime). lotItemCategory -> id offset.
ITEM_NAME_CAT_OFFSET = {1: 500000000, 2: 100000000, 3: 200000000,
                        4: 300000000, 5: 400000000}


def _load_json(path):
    return json.load(open(path, encoding="utf-8")) if path.exists() else None


def generate_name_aliases_en_cpp(output_path):
    """Generate goblin_name_aliases_en.cpp: an English name-alias table for the F1
    marker search, keyed by the encoded name id the markers carry. Aggregates every
    committed English-name source (always extracted from the engus FMGs), so search
    matches the English/wiki name regardless of the player's game language:
      items   from items_database.json (encode_live_item offsets)
      NPCs    from npc_name_text_map.json (id + 700M)
      enemies from enemy_names_i18n.json engus column (id + 900M)
      bosses  from boss_list.json wmpTextId1 -> vanillaPlaceName (raw)."""
    import config
    data = config.PROJECT_DIR / "data"
    table = {}  # encoded_id -> English name (first-wins; sources ordered by priority)

    def add(enc, nm):
        # Marker::name_id is int32; an out-of-range encoded id can never match a
        # marker (e.g. the INT32_MAX "ERR dummy" NpcName sentinel) — drop it.
        if enc and -2**31 <= enc < 2**31 and nm and "<" not in nm:
            table.setdefault(enc, nm)

    # Items (offset-encoded by lotItemCategory).
    db = _load_json(data / "items_database.json")
    for lot in (db or []):
        for it in (lot.get("items") or []):
            off = ITEM_NAME_CAT_OFFSET.get(it.get("category"))
            if off is not None and it.get("id") is not None:
                add(it["id"] + off, it.get("name"))

    # Named NPCs (hostile invaders / quest NPCs): marker textId = nameId + 700M.
    npc = _load_json(data / "npc_name_text_map.json")
    for k, v in (npc or {}).items():
        add(int(k) + 700000000, v)

    # (Enemy-drop labels now resolve from the killed enemy's live NpcParam.nameId
    # via GetMessage(NpcName); those names are already covered by the +700M NPC block
    # above, so the old +900M enemy/Codex search-alias source is gone.)

    # Bosses: the baked marker carries the raw WorldMapPlaceName textId1.
    for b in (_load_json(data / "boss_list.json") or []):
        add(b.get("wmpTextId1"), b.get("vanillaPlaceName"))

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED FILE - DO NOT EDIT\n")
        f.write("// Generated by tools/generate_data.py from items_database.json,\n")
        f.write("// npc_name_text_map.json, enemy_names_i18n.json, boss_list.json\n\n")
        f.write('#include "goblin_name_aliases_en.hpp"\n\n')
        f.write("namespace goblin::generated\n{\n\n")
        f.write(f"const size_t NAME_ALIAS_EN_COUNT = {len(table)};\n\n")
        f.write("const NameAliasEn NAME_ALIASES_EN[] = {\n")
        for enc in sorted(table):
            f.write(f"    {{{enc}, {_wlit(table[enc])}}},\n")
        if not table:
            f.write("    {0, nullptr},\n")
        f.write("};\n\n")
        f.write("} // namespace goblin::generated\n")
    print(f"Generated {output_path} with {len(table)} English name aliases")


def main():
    # NOTE: this generator no longer reads any MASSEDIT input. The marker bake
    # was retired (generate_map_data_cpp writes an unconditional empty stub), so
    # the old --massedit-dir arg is gone; the real outputs (category_exceptions,
    # name_aliases, legacy_conv) are built from JSON tables, not .MASSEDIT.
    script_dir = Path(__file__).parent
    project_dir = script_dir.parent

    import config
    output_dir = config.GENERATED_DIR  # src/generated or src/generated_vanilla

    output_dir.mkdir(parents=True, exist_ok=True)

    # goblin_map_data.hpp (the Category enum + struct) is a static, profile-
    # independent header with no generator. The canonical copy lives in
    # src/generated/; mirror it into a non-default bake dir (e.g. vanilla) so
    # that dir is self-contained for the compiler's include path.
    import shutil
    for hdr in ("goblin_map_data.hpp",
                "goblin_category_exceptions.hpp",
                "goblin_name_aliases_en.hpp"):
        canonical_hpp = project_dir / "src" / "generated" / hdr
        dest_hpp = output_dir / hdr
        if canonical_hpp.resolve() != dest_hpp.resolve():
            shutil.copyfile(canonical_hpp, dest_hpp)

    # goblin_tile_tabs.{hpp,cpp} (player MapId tile -> map sub-page tabId, from
    # build_tile_tabs.py) is profile-independent — the game's tiling is identical
    # across bakes — so mirror the committed canonical pair into a non-default dir.
    for f in ("goblin_tile_tabs.hpp", "goblin_tile_tabs.cpp",
              "goblin_major_regions.hpp", "goblin_major_regions.cpp"):
        canonical = project_dir / "src" / "generated" / f
        dest = output_dir / f
        if canonical.exists() and canonical.resolve() != dest.resolve():
            shutil.copyfile(canonical, dest)

    print("=== Generating map data C++ (no-bake stub) ===")
    generate_map_data_cpp(output_dir / "goblin_map_data.cpp")

    print("\n=== Generating category-exceptions table C++ ===")
    generate_category_exceptions_cpp(output_dir / "goblin_category_exceptions.cpp")

    print("\n=== Generating English name-alias table C++ ===")
    generate_name_aliases_en_cpp(output_dir / "goblin_name_aliases_en.cpp")

    print("\n=== Generating legacy-conv C++ ===")
    generate_legacy_conv_cpp(config.DATA_DIR / "WorldMapLegacyConvParam.json",
                             output_dir / "goblin_legacy_conv.hpp")

    print("\nDone.")


def generate_legacy_conv_cpp(conv_json, output_path):
    """Emit a C++ header with the dungeon→overworld conversion table.
    Used by goblin_markers to place dungeon MAP_ENTRIES on overworld coords."""
    if not conv_json.exists():
        print(f"  WARNING: {conv_json} missing, skipping")
        return
    rows = json.load(open(conv_json, encoding='utf-8'))
    # Parse every hop. The param maps a sub-area onto another area; many dungeon
    # sub-areas reach the overworld (60/61) only TRANSITIVELY — e.g. Leyndell's
    # Ashen Capital m35 -> area 11 (Leyndell) -> area 60. A single-hop filter
    # (dst in 60/61) silently drops those, so follow the chains and compose the
    # translations down to 60/61.
    hops = []
    for r in rows:
        if not isinstance(r, dict): continue
        hops.append({
            'src_area': int(r.get('srcAreaNo', 0)),
            'src_gx': int(r.get('srcGridXNo', 0)),
            'src_gz': int(r.get('srcGridZNo', 0)),
            'src_pos_x': float(r.get('srcPosX', 0)),
            'src_pos_z': float(r.get('srcPosZ', 0)),
            'dst_area': int(r.get('dstAreaNo', 0)),
            'dst_gx': int(r.get('dstGridXNo', 0)),
            'dst_gz': int(r.get('dstGridZNo', 0)),
            'dst_pos_x': float(r.get('dstPosX', 0)),
            'dst_pos_z': float(r.get('dstPosZ', 0)),
        })
    by_src = {}   # (area, gx) -> first hop
    by_area = {}  # area -> first hop (grid fallback)
    for h in hops:
        by_src.setdefault((h['src_area'], h['src_gx']), h)
        by_area.setdefault(h['src_area'], h)

    def w(gx, pos): return gx * 256.0 + pos

    def resolve(h, seen):
        """Compose chains until dst is 60/61; None if it never reaches overworld."""
        if h['dst_area'] in (60, 61):
            return h
        if h['dst_area'] in seen:  # cycle guard
            return None
        nxt = by_src.get((h['dst_area'], h['dst_gx'])) or by_area.get(h['dst_area'])
        if not nxt:
            return None
        r = resolve(nxt, seen | {h['dst_area']})
        if not r:
            return None
        # Translate H's dst world point by R's (dst - src) offset.
        cx = w(h['dst_gx'], h['dst_pos_x']) + w(r['dst_gx'], r['dst_pos_x']) - w(r['src_gx'], r['src_pos_x'])
        cz = w(h['dst_gz'], h['dst_pos_z']) + w(r['dst_gz'], r['dst_pos_z']) - w(r['src_gz'], r['src_pos_z'])
        gx, gz = int(cx // 256), int(cz // 256)
        return {**h, 'dst_area': r['dst_area'], 'dst_gx': gx, 'dst_gz': gz,
                'dst_pos_x': cx - gx * 256.0, 'dst_pos_z': cz - gz * 256.0}

    by_key = {}
    for h in hops:
        key = (h['src_area'], h['src_gx'])
        if key in by_key:
            continue
        res = resolve(h, {h['src_area']})
        if res:
            by_key[key] = res
    entries = sorted(by_key.values(), key=lambda e: (e['src_area'], e['src_gx']))
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("#pragma once\n// AUTO-GENERATED — do not edit.\n")
        f.write("// Dungeon-area → overworld-tile conversion table (first base-point per src key,\n")
        f.write("// transitively composed down to area 60/61 — e.g. Ashen Capital m35→11→60).\n\n")
        f.write("#include <cstdint>\n#include <cstddef>\n\n")
        f.write("namespace goblin::generated {\n\n")
        f.write("struct LegacyConvEntry {\n")
        f.write("    uint8_t src_area;\n    uint8_t src_gx;\n    uint8_t src_gz;\n")
        f.write("    float src_pos_x;\n    float src_pos_z;\n")
        f.write("    uint8_t dst_area;\n    uint8_t dst_gx;\n    uint8_t dst_gz;\n")
        f.write("    float dst_pos_x;\n    float dst_pos_z;\n")
        f.write("};\n\n")
        f.write(f"constexpr LegacyConvEntry LEGACY_CONV[] = {{\n")
        for e in entries:
            f.write(f"    {{ {e['src_area']}, {e['src_gx']}, {e['src_gz']}, {e['src_pos_x']:.3f}f, {e['src_pos_z']:.3f}f, ")
            f.write(f"{e['dst_area']}, {e['dst_gx']}, {e['dst_gz']}, ")
            f.write(f"{e['dst_pos_x']:.3f}f, {e['dst_pos_z']:.3f}f }},\n")
        f.write("};\n\n")
        f.write(f"constexpr size_t LEGACY_CONV_COUNT = {len(entries)};\n\n")
        f.write("} // namespace goblin::generated\n")
    print(f"  Generated {output_path.name} with {len(entries)} conv entries")


if __name__ == "__main__":
    main()
