#!/usr/bin/env python3
"""Generate the Quest Browser step table (Thread 1, quest navigation menu).

Source: data/questlog_english.lang — the English strings of the MIT-licensed
EldenRingQuestLog (github.com/EldenRingQuestGiver/EldenRingQuestLog, (c) 2024
TheHaist; see data/QUESTLOG_LICENSE). Each NPC quest is a base id 87NN0000:
  base+0           = quest title  ("Corhyn's Quest")
  base+step*100+0  = step title    ("Pious Man")
  base+step*100+1  = step descr    ("You spoke with Brother Corhyn at ...")
Steps are emitted in ascending order. The description carries the LOCATION in
prose ("Roundtable Hold", "Altus Plateau") — Phase A lists this text; the map
reveal (matching the location name to a marker region) is Phase B.

Output: src/generated/goblin_quest_steps.{hpp,cpp} — an ordered table the
overlay's Quest Browser walks. Pure stdlib; re-run if the lang file changes.
"""
import json
import os
import re

HERE = os.path.dirname(__file__)
LANG = os.path.join(HERE, "..", "data", "questlog_english.lang")
OUT_HPP = os.path.join(HERE, "..", "src", "generated", "goblin_quest_steps.hpp")
OUT_CPP = os.path.join(HERE, "..", "src", "generated", "goblin_quest_steps.cpp")

# npc key -> (quest base id, display name). Bases verified from
# EldenRingQuestLog src/erquestlog_quests.hpp (ADD_TALK_LIST_IF_DATA_ARGS).
NPCS = [
    ("irina", 87010000, "Irina"),
    ("roderika", 87020000, "Roderika"),
    ("sellen", 87030000, "Sorceress Sellen"),
    ("kenneth", 87040000, "Kenneth Haight"),
    ("boc", 87050000, "Boc the Seamster"),
    ("blaidd", 87060000, "Blaidd"),
    ("thops", 87070000, "Sorcerer Thops"),
    ("patches", 87080000, "Patches"),
    ("ranni", 87090000, "Ranni the Witch"),
    ("rya", 87100000, "Rya"),
    ("gowry", 87110000, "Gowry"),
    ("d", 87120000, "D, Hunter of the Dead"),
    ("gurranq", 87130000, "Gurranq"),
    ("diallos", 87140000, "Diallos"),
    ("seluvis", 87150000, "Seluvis"),
    ("dungeater", 87160000, "Dung Eater"),
    ("rogier", 87170000, "Rogier"),
    ("nepheli", 87180000, "Nepheli Loux"),
    ("hyetta", 87190000, "Hyetta"),
    ("alexander", 87200000, "Alexander"),
    ("yura", 87210000, "Yura"),
    ("fia", 87220000, "Fia"),
    ("varre", 87230000, "White Mask Varre"),
    ("millicent", 87240000, "Millicent"),
    ("jarbairn", 87250000, "Jar-Bairn"),
    ("corhyn", 87260000, "Brother Corhyn / Goldmask"),
    ("latenna", 87270000, "Latenna"),
    ("bernahl", 87280000, "Bernahl"),
    ("ansbach", 87290000, "Ansbach"),
    ("hornsent", 87310000, "Hornsent"),
    ("queelign", 87320000, "Queelign"),
    ("ymir", 87330000, "Count Ymir"),
    ("igon", 87340000, "Igon"),
    ("trina", 87350000, "St. Trina"),
]


def cesc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "")


_LINE = re.compile(r'^"(\d+)"\s*:\s*"(.*)"\s*,?\s*$')


def load_lang(path):
    """The .lang is one `"id": "text"` per line (not a JSON object). Parse to a
    dict, unescaping \\" and stripping the HTML/markdown the mod uses for its own
    UI (<img ...> tags, __bold__) that we don't want in plain ImGui text."""
    out = {}
    for line in open(path, encoding="utf-8"):
        m = _LINE.match(line.rstrip("\n"))
        if not m:
            continue
        val = m.group(2).replace('\\"', '"')
        val = re.sub(r"<[^>]+>", "", val)   # drop HTML tags
        val = val.replace("__", "")          # drop markdown bold markers
        out[m.group(1)] = val.strip()
    return out


def main():
    lang = load_lang(LANG)

    def get(k):
        v = lang.get(str(k))
        return v.strip() if v else None

    npcs_out = []   # (key, name, quest_title, [(title, desc), ...])
    total_steps = 0
    for key, base, name in NPCS:
        quest_title = get(base) or name
        steps = []
        for step in range(1, 64):
            t = get(base + step * 100 + 0)
            d = get(base + step * 100 + 1)
            if not t and not d:
                # allow a one-step gap (some quests skip a number), stop on two
                if step > 1 and not get(base + (step + 1) * 100 + 0) \
                        and not get(base + (step + 1) * 100 + 1):
                    break
                continue
            steps.append((t or "", d or ""))
        npcs_out.append((key, name, quest_title, steps))
        total_steps += len(steps)

    with open(OUT_HPP, "w", encoding="utf-8") as f:
        f.write("#pragma once\n")
        f.write("// AUTO-GENERATED by tools/generate_quest_browser.py\n")
        f.write("// Quest step text from EldenRingQuestLog (MIT, (c) 2024 TheHaist);\n")
        f.write("// see data/QUESTLOG_LICENSE.\n")
        f.write("#include <cstddef>\n\nnamespace goblin::generated\n{\n")
        f.write("struct QuestStep { const char *title; const char *desc; };\n")
        f.write("struct NpcQuest { const char *name; const char *quest_title;\n")
        f.write("                  const QuestStep *steps; size_t step_count; };\n")
        f.write("extern const NpcQuest QUEST_BROWSER[];\n")
        f.write("extern const size_t QUEST_BROWSER_COUNT;\n\n} // namespace\n")

    with open(OUT_CPP, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by tools/generate_quest_browser.py\n")
        f.write("// Quest step text from EldenRingQuestLog (MIT, (c) 2024 TheHaist).\n")
        f.write('#include "goblin_quest_steps.hpp"\n\nnamespace goblin::generated\n{\n')
        for key, name, qt, steps in npcs_out:
            f.write("static const QuestStep steps_%s[] = {\n" % key)
            for t, d in steps:
                f.write('    {"%s", "%s"},\n' % (cesc(t), cesc(d)))
            f.write("};\n")
        f.write("\nconst NpcQuest QUEST_BROWSER[] = {\n")
        for key, name, qt, steps in npcs_out:
            f.write('    {"%s", "%s", steps_%s, %d},\n'
                    % (cesc(name), cesc(qt), key, len(steps)))
        f.write("};\nconst size_t QUEST_BROWSER_COUNT = %d;\n\n} // namespace\n"
                % len(npcs_out))

    print("wrote %d NPC quests, %d steps total" % (len(npcs_out), total_steps))


if __name__ == "__main__":
    main()
