"""Generate src/generated/goblin_geof_models.{hpp,cpp} — per-row ACTUAL gather-asset models.

In ERR's MSBs some gather parts keep their vanilla NAME but reference a different MODEL
(e.g. part AEG099_753_9000 with ModelName AEG463_860 — the DLC-era Sacramental Burgeon).
The game instantiates by model, so GeomFlagSaveDataManager records picks under the ACTUAL
model's hash. Collected-tracking that buckets GEOF slots by the part-NAME prefix misses
those entries and the icon stays visible while the tile is unloaded (visible-after-restart
bug). This table maps marker row_id -> actual model id for every row where they differ
(247 nodes: 753->860/771, 760->660/661, 720->710, 651->770, ...).

Reads goblin_map_data.cpp (row_id + object_name + tile) and all_gathering_nodes_final.json
((map, name) -> model). Must run AFTER generate_data.

Usage: py generate_geof_models.py
"""
import os, sys, io, re, json
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))
import config
D = str(config.DATA_DIR)              # data/ or data/vanilla/
GEN = str(config.GENERATED_DIR)       # src/generated or src/generated_vanilla
os.makedirs(GEN, exist_ok=True)

def model_id(model):  # "AEG463_860" -> 10463860 (= GEOF model hash)
    return 10000000 + int(model[3:6]) * 1000 + int(model[7:10])

nodes = {}
for n in json.load(open(os.path.join(D, "all_gathering_nodes_final.json"), encoding="utf-8")):
    nodes[(n["map"], n["name"].split(" {")[0])] = n["model"]  # strip ' {N}' dup decoration

# Phase 2: the compiled goblin_map_data.cpp is an empty stub; read the FULL table from the
# uncompiled pipeline intermediate generate_data.py writes (same '// Row ID' .cpp format).
txt = open(os.path.join(D, "_map_entries_full.cpp"), encoding="utf-8").read()
rows = []
for b in txt.split("// Row ID ")[1:]:
    rid = b.split("\n", 1)[0].strip()
    nm = re.search(r'\"(AEG\d{3}_\d{3}_\d{4})\"', b)
    if not nm:
        continue
    name = nm.group(1)
    area = re.search(r"\.areaNo = (\d+)", b)
    gx = re.search(r"\.gridXNo = (\d+)", b)
    gz = re.search(r"\.gridZNo = (\d+)", b)
    mapname = f"m{int(area.group(1)) if area else 0:02d}_{int(gx.group(1)) if gx else 0:02d}_{int(gz.group(1)) if gz else 0:02d}_00"
    model = nodes.get((mapname, name))
    if not model:
        continue
    name_prefix = name.rsplit("_", 1)[0]
    if model != name_prefix:
        rows.append((int(rid), model_id(model), name, model))
rows.sort()

with open(os.path.join(GEN, "goblin_geof_models.hpp"), "w", encoding="utf-8") as f:
    f.write("""#pragma once

#include <cstddef>
#include <cstdint>

namespace goblin::generated
{

// Rows whose gather part NAME differs from its ACTUAL model (ERR substituted the asset,
// e.g. part AEG099_753_9000 instantiates DLC model AEG463_860). GEOF save entries carry
// the ACTUAL model's hash — collected-tracking must bucket these rows by it.
struct GeofModelOverride
{
    uint64_t row_id;    // ORIGINAL (pre-remap) row id, matches MAP_ENTRIES[].row_id
    uint32_t model_id;  // actual model id (10463860 = AEG463_860) as seen in GEOF entries
};

extern const GeofModelOverride GEOF_MODEL_OVERRIDES[];  // sorted by row_id
extern const size_t GEOF_MODEL_OVERRIDE_COUNT;

} // namespace goblin::generated
""")
with open(os.path.join(GEN, "goblin_geof_models.cpp"), "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED FILE - DO NOT EDIT\n")
    f.write("// Generated by tools/generate_geof_models.py from goblin_map_data.cpp + all_gathering_nodes_final.json\n\n")
    f.write('#include "goblin_geof_models.hpp"\n\n')
    f.write("namespace goblin::generated\n{\n\n")
    f.write(f"const size_t GEOF_MODEL_OVERRIDE_COUNT = {len(rows)};\n\n")
    f.write("const GeofModelOverride GEOF_MODEL_OVERRIDES[] = {\n")
    for rid, mid, name, model in rows:
        f.write(f"    {{{rid}ull, {mid}u}},  // {name} -> {model}\n")
    if not rows:
        f.write("    {0ull, 0u},\n")
    f.write("};\n\n} // namespace goblin::generated\n")
print(f"wrote {len(rows)} model overrides -> {GEN}/goblin_geof_models.cpp")
from collections import Counter
print(Counter(f"{n.rsplit('_',1)[0]} -> {m}" for _, _, n, m in rows))
