#!/usr/bin/env python3
"""Generate src/generated/goblin_world_feature_models.{hpp,cpp} from the editorial
tools/world_feature_assets.py table.

The runtime's ONE generic World-feature pass (build_disk_world_feature_markers in
map_entry_layer.cpp) scans the mod's real MSB AEG asset placements, looks each
aegRow up in WORLD_FEATURE_MODELS, and emits a marker — so off-baking a new
asset-model World feature is ONE row in world_feature_assets.py, zero C++.

Profile-independent editorial data (no MSB/regulation read) — writes the same table
to whatever config.GENERATED_DIR resolves to (src/generated or src/generated_vanilla).

Usage: py generate_world_feature_models.py
"""
import os, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import config
from world_feature_assets import WORLD_FEATURE_ASSETS

GEN = str(config.GENERATED_DIR)       # src/generated or src/generated_vanilla
os.makedirs(GEN, exist_ok=True)

rows = sorted(WORLD_FEATURE_ASSETS, key=lambda r: r['aeg_row'])

# python flag_rule string -> C++ FlagRule enumerator
FLAG_RULE_CPP = {'none': 'None', 'imp_seal': 'ImpSeal', 'hero_tomb_emevd': 'HeroTombEmevd',
                 'seal_emevd': 'SealEmevd'}

HPP = """#pragma once

#include <cstddef>
#include <cstdint>

#include "goblin_map_data.hpp"  // Category enum

namespace goblin::generated
{

// How the runtime derives a World feature's graying flag (marker textDisableFlagId1), so an
// activated/looted instance hides like the bake did — resolved LIVE from the mod's files, no bake:
//   None          no flag (respawn points, never "complete").
//   ImpSeal       flag = tile_base(area,gx,gz) + (entityId % 1000); the pass also rejects
//                 placements whose entity suffix isn't a real seal {570,575,565,611} and picks
//                 the key label by suffix (565 = Imbued Sword Key, else Stonesword Key).
//   HeroTombEmevd flag = the EMEVD template-90005683 activated flag, joined to the asset by EntityID.
//   SealEmevd     flag = the EMEVD template-90006051 activation flag, joined by EntityID; the pass
//                 SELF-GATES (skips placements with no 90006051 binding = decoration / non-seal use).
enum class FlagRule : uint8_t { None, ImpSeal, HeroTombEmevd, SealEmevd };

// One asset-model World feature: an AEG ModelName that maps to a marker category.
// The runtime's generic disk pass (build_disk_world_feature_markers) emits a marker
// for every placed MSB asset whose aegRow matches a row here. Generated from
// tools/world_feature_assets.py — add a feature there, not in C++.
struct WorldFeatureModel
{
    uint32_t aeg_row;          // AssetEnvironmentGeometryParam row id (AEG{A}_{B} -> A*1000+B)
    Category category;         // marker bucket
    int32_t  text_id;          // WorldMapPointParam.textId1 for the tooltip label
    bool     entity_required;  // true = emit only placements carrying an MSB EntityID (interactive)
    bool     category_wipe;    // true = drop ALL baked of this category (dedicated); false = cell-dedup (shared)
    FlagRule flag_rule;        // how the pass resolves the graying flag (+ Imp suffix filter/label)
    bool     lod_scan;         // true = model lives only in non-_00 LOD supertiles; the world-feature
                               // pass adds a targeted non-_00 asset scan (load_lod_feature_assets)
};

extern const WorldFeatureModel WORLD_FEATURE_MODELS[];  // sorted by aeg_row
extern const size_t WORLD_FEATURE_MODEL_COUNT;

} // namespace goblin::generated
"""

with open(os.path.join(GEN, "goblin_world_feature_models.hpp"), "w", encoding="utf-8") as f:
    f.write(HPP)

with open(os.path.join(GEN, "goblin_world_feature_models.cpp"), "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED FILE - DO NOT EDIT\n")
    f.write("// Generated by tools/generate_world_feature_models.py from tools/world_feature_assets.py\n\n")
    f.write('#include "goblin_world_feature_models.hpp"\n\n')
    f.write("namespace goblin::generated\n{\n\n")
    f.write(f"const size_t WORLD_FEATURE_MODEL_COUNT = {len(rows)};\n\n")
    f.write("const WorldFeatureModel WORLD_FEATURE_MODELS[] = {\n")
    for r in rows:
        f.write("    {{{row}u, Category::{cat}, {tid}, {ent}, {wipe}, FlagRule::{rule}, {lod}}},  // {model} {feat}\n".format(
            row=r['aeg_row'], cat=r['category'], tid=r['text_id'],
            ent='true' if r['entity_required'] else 'false',
            wipe='true' if r['category_wipe'] else 'false',
            rule=FLAG_RULE_CPP[r['flag_rule']],
            lod='true' if r.get('lod_scan') else 'false',
            model=r['model'], feat=r['category']))
    f.write("};\n\n} // namespace goblin::generated\n")

print(f"wrote {len(rows)} world-feature models -> {GEN}/goblin_world_feature_models.cpp")
for r in rows:
    print(f"  {r['model']:14s} aegRow={r['aeg_row']:<6} -> {r['category']:22s} "
          f"entity={'Y' if r['entity_required'] else 'n'} "
          f"{'wipe' if r['category_wipe'] else 'cell'} flag={r['flag_rule']}"
          f"{' LOD-scan' if r.get('lod_scan') else ''}")
