#!/usr/bin/env python3
"""
Generate the live runtime C++ tables (NOT the marker bake — that was retired in Phase 2).

Emits:
  - src/generated/goblin_map_data.cpp        (Phase-2 empty no-bake stub; markers come live/disk)

The dungeon->overworld conversion table (goblin_legacy_conv.hpp) was DELETED
2026-07-05 (imgui_only_map_plan Track C): the DLL folds it LIVE from the resident
regulation param via goblin::legacy_fold, so no baked snapshot is emitted.

Localization is handled by the DLL at runtime via FMG offset-encoding
(textId = real_id + category_offset), so no text compilation step is needed.
"""

import os
import sys
from pathlib import Path

# Phase-2 no-bake stub written to the COMPILED goblin_map_data.cpp. The static marker bake is
# retired — every marker comes from live mod files / game memory at runtime — so the compiled
# table is empty. A 0-length array is ill-formed, so a 1-elem zero dummy is emitted and never
# read (every consumer iterates `i < MAP_ENTRY_COUNT` == 0). The Category enum + MapEntry types
# stay in goblin_map_data.hpp (they drive the overlay layers/buckets).
_MAP_DATA_STUB = (
    "// AUTO-GENERATED FILE - DO NOT EDIT\n"
    "// Generated by tools/generate_data.py — PHASE-2 NO-BAKE STUB (the static marker bake is\n"
    "// retired; every marker comes from live mod files / game memory at runtime). The full\n"
    "// MapEntry table is no longer materialised anywhere — the last consumers of it\n"
    "// (generate_geof_models, generate_location_overrides) were retired in the Phase-2 cleanup.\n\n"
    '#include "goblin_map_data.hpp"\n\n'
    "namespace goblin::generated\n{\n\n"
    "const size_t MAP_ENTRY_COUNT = 0;\n\n"
    "// Never read (COUNT == 0 gates every consumer loop); a 0-length array is ill-formed.\n"
    "const MapEntry MAP_ENTRIES[1] = {};\n\n"
    "} // namespace goblin::generated\n"
)


def generate_map_data_cpp(output_path):
    """Phase 2 (no-bake): the COMPILED goblin_map_data.cpp is an EMPTY STUB. The full MapEntry
    table used to be emitted to an uncompiled intermediate for two downstream generators, but both
    (generate_geof_models, generate_location_overrides) were retired — the gather model now comes
    live from the MSB part modelIndex and the location names from the runtime resolver — so nothing
    text-parses the table any more. We just write the constant stub."""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(_MAP_DATA_STUB)
    print(f"Generated {output_path} (Phase-2 empty no-bake stub)")




# NOTE: the F1-search English name-alias table (generate_name_aliases_en_cpp,
# emitting goblin_name_aliases_en.cpp) was REMOVED 2026-07-01 — English names now
# resolve live from the active install's engus FMGs on disk at runtime
# (src/worldmap/name_fmg_en.cpp). See docs/plans/baked_data_full_removal_plan.md.


def main():
    # NOTE: this generator no longer reads any MASSEDIT input. The marker bake
    # was retired (generate_map_data_cpp writes an unconditional empty stub), so
    # the old --massedit-dir arg is gone; the real outputs (category_exceptions,
    # name_aliases, legacy_conv) are built from JSON tables, not .MASSEDIT.
    script_dir = Path(__file__).parent
    project_dir = script_dir.parent

    import config
    output_dir = config.GENERATED_DIR  # src/generated or src/generated_vanilla

    output_dir.mkdir(parents=True, exist_ok=True)

    # goblin_map_data.hpp (the Category enum + struct) is a static, profile-
    # independent header with no generator. The canonical copy lives in
    # src/generated/; mirror it into a non-default bake dir (e.g. vanilla) so
    # that dir is self-contained for the compiler's include path.
    import shutil
    for hdr in ("goblin_map_data.hpp",):
        canonical_hpp = project_dir / "src" / "generated" / hdr
        dest_hpp = output_dir / hdr
        if canonical_hpp.resolve() != dest_hpp.resolve():
            shutil.copyfile(canonical_hpp, dest_hpp)

    # goblin_tile_tabs.{hpp,cpp} (player MapId tile -> map sub-page tabId, from
    # build_tile_tabs.py) is profile-independent — the game's tiling is identical
    # across bakes — so mirror the committed canonical pair into a non-default dir.
    for f in ("goblin_tile_tabs.hpp", "goblin_tile_tabs.cpp",
              "goblin_major_regions.hpp", "goblin_major_regions.cpp"):
        canonical = project_dir / "src" / "generated" / f
        dest = output_dir / f
        if canonical.exists() and canonical.resolve() != dest.resolve():
            shutil.copyfile(canonical, dest)

    print("=== Generating map data C++ (no-bake stub) ===")
    generate_map_data_cpp(output_dir / "goblin_map_data.cpp")

    # Category descriptor (data/categories.json -> goblin_categories.gen.hpp). Keeps the
    # committed generated header in sync so name/section never drift from the table.
    print("\n=== Generating category descriptor ===")
    import generate_categories
    generate_categories.main()

    print("\nDone.")


if __name__ == "__main__":
    main()
