#!/usr/bin/env python3
"""Render docs/item_classification.md from the runtime [ITEMCLASS] log.

The provenance scoreboard (nobake_scoreboard.md) tracks WHERE a marker comes from
(baked/disk/live) per category, but NOT which CATEGORY each item lands in. That blind spot
let the ERR rune variants (goods 82909-82919) silently fall into Crafting Materials instead
of Golden Runes. This doc closes it: every DISTINCT item the runtime classified via the LIVE
fallback (classify_item_live — i.e. absent from the static ITEM_ICONS table) + the category it
landed in. A mis-classification shows up as a row in the wrong bucket; a future regression shows
up as a `git diff`. Table-backed items are NOT here — they're pinned in goblin_item_icons.cpp
(diff that file directly). Rows are sorted by (category, key) so the diff is stable: a row only
changes when an item's CATEGORY changes (a real regression) or the mod adds/removes an item.

Source: the latest `[ITEMCLASS]` block from build_buckets_impl (one per map build). Run the game
with the overlay, open the map, then:
  py -3.14 tools/item_classification.py [path\\to\\MapForGoblins.log]
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_LOG = (r"D:\DOWNLOAD\ERRv2.2.9.6-541-2-2-9-6-1780861369\ERRv2.2.9.6"
               r"\dll\offline\logs\MapForGoblins.log")
OUT = os.path.join(ROOT, "docs", "item_classification.md")

HEADER = re.compile(r"\[ITEMCLASS\] live-fallback classifications \((?P<n>\d+) distinct")
ROW = re.compile(r'\[ITEMCLASS\] key=(?P<key>-?\d+) cat="(?P<cat>[^"]+)" count=(?P<count>\d+)')

log = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_LOG

# Parse the LATEST [ITEMCLASS] block (reset on each header line).
rows = {}  # key -> (category, count)
for line in open(log, encoding="utf-8", errors="replace"):
    if HEADER.search(line):
        rows = {}
        continue
    m = ROW.search(line)
    if m:
        rows[int(m.group("key"))] = (m.group("cat"), int(m.group("count")))
if not rows:
    sys.exit("no [ITEMCLASS] lines — run the game (overlay on) + open the map, then re-run.")


# Resolve the item NAME from the +Nx100M encoded key. Best-effort: needs the FMG (via the
# pythonnet/SoulsFormats pipeline). If it can't load, the doc still renders (name = "?").
def load_names():
    try:
        import os as _os
        import tempfile
        import extract_all_items as E
        from System import Array, Object
        from System.IO import File as SysFile
        tmp = _os.path.join(tempfile.gettempdir(), f"mfg_ic_{_os.getpid()}.bnd")
        SysFile.WriteAllBytes(tmp, E.SoulsFormats.DCX.Decompress(str(E.MSGBND_PATH)).ToArray())
        msg = E._bnd4_read.Invoke(None, Array[Object]([tmp]))
        try:
            _os.unlink(tmp)
        except OSError:
            pass
        return {1: E.read_fmg_names(msg, "GoodsName.fmg"),
                2: E.read_fmg_names(msg, "WeaponName.fmg"),
                3: E.read_fmg_names(msg, "ProtectorName.fmg"),
                4: E.read_fmg_names(msg, "AccessoryName.fmg"),
                5: E.read_fmg_names(msg, "GemName.fmg")}
    except Exception as e:
        print(f"  (FMG names unavailable: {e} — rendering without names)")
        return {}


NAMES = load_names()


def decode(key):
    """+Nx100M key -> (item id, FMG table 1..5). Mirrors encode_live_item / classify_item_live."""
    if key >= 500000000:
        return key - 500000000, 1           # goods
    if key >= 400000000:
        return key - 400000000, 5           # gem
    if key >= 300000000:
        return key - 300000000, 4           # accessory
    if key >= 200000000:
        return key - 200000000, 3           # protector
    if key >= 100000000:
        return key - 100000000, 2           # weapon/ammo
    return key, 0


def name_of(key):
    iid, tbl = decode(key)
    return NAMES.get(tbl, {}).get(iid, "?")


# Group by category, sort rows by (category, key) for a stable diff.
by_cat = {}
for key, (cat, _count) in rows.items():
    by_cat.setdefault(cat, []).append(key)

ts = "?"
for line in reversed(open(log, encoding="utf-8", errors="replace").readlines()):
    m = re.match(r"^\[(?P<ts>[\d\-: .]+)\]", line)
    if m:
        ts = m.group("ts")
        break

lines = []
lines.append("# Item classification — live-fallback surface")
lines.append("")
lines.append("> Generated by `tools/item_classification.py` from the runtime `[ITEMCLASS]` log. "
             "Do not edit by hand.")
lines.append("")
lines.append("Every **distinct item** the runtime classified via the **live fallback** "
             "(`classify_item_live`) — i.e. items NOT in the static `ITEM_ICONS` table, so "
             "`item_marker_category` missed them. This is the drift-prone surface: a "
             "mis-classified item appears below in the wrong category. **Regression guard:** after a "
             "classification change, regenerate and `git diff` this file — a row only moves when an "
             "item's category changes. Table-backed items are pinned in "
             "`src/generated/goblin_item_icons.cpp` (diff there).")
lines.append("")
lines.append(f"_{len(rows)} distinct live-classified items across {len(by_cat)} categories "
             f"(log {ts})._")
lines.append("")
for cat in sorted(by_cat):
    keys = sorted(by_cat[cat])
    lines.append(f"## {cat}  ({len(keys)})")
    lines.append("")
    lines.append("| item | key | id |")
    lines.append("|---|---|---|")
    for key in keys:
        iid, _tbl = decode(key)
        lines.append(f"| {name_of(key)} | {key} | {iid} |")
    lines.append("")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT}  ({len(rows)} items, {len(by_cat)} categories)")
