#!/usr/bin/env python3
"""Coverage report: items the game HAS in a category but never PLACES on the map / in an F1 toggle.

The provenance scoreboard (nobake_scoreboard.md) + item_classification.md track what IS drawn and
how it's classified. This is the inverse: per F1 category, the known goods that classify INTO it but
have no marker — the "you'll never find one of these in the world" gaps. Useful for spotting coverage
holes and for sanity-checking the live classifier against the full item universe.

Universe  = every EquipParamGoods row (data/goods_type_sortgroup.json), classified by the SHARED
            offline mirror of the DLL classifier (taxonomy_classifier.py — kept in lock-step with
            goblin_inject.cpp). GOODS only (weapons/armour are non-goods and number in the thousands).
Placed    = goods that appear in data/item_icon_table.json (the bake's placed-item set across every
            loot mechanism — the best offline proxy for "has a marker"). NOTE: a randomizer or another
            mod places a different set; this is the ERR-bake baseline.
Unplaced  = (universe in category) − placed,  for the CONFIDENT categories only (the catch-all /
            key-item tail is the uncertain surface, reported separately as a count).

Run (names need SoulsFormats; without it the report still renders with name='?'):
  PYTHONUTF8=1 PYTHONPATH="C:/Users/iamacat/AppData/Local/Temp/mfg_aux" MFG_PROFILE=err \
    py -3.14 tools/unplaced_items.py
"""
import os
import sys
import json
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import taxonomy_classifier as TC

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'data')
OUT = os.path.join(ROOT, 'docs', 'unplaced_items.md')


def load_goods_names():
    """{goods_id: name} from GoodsName FMG — best-effort (needs SoulsFormats/pythonnet)."""
    try:
        import os as _os
        import tempfile
        import extract_all_items as E
        from System import Array, Object
        from System.IO import File as SysFile
        tmp = _os.path.join(tempfile.gettempdir(), f'mfg_unpl_{_os.getpid()}.bnd')
        SysFile.WriteAllBytes(tmp, E.SoulsFormats.DCX.Decompress(str(E.MSGBND_PATH)).ToArray())
        msg = E._bnd4_read.Invoke(None, Array[Object]([tmp]))
        try:
            _os.unlink(tmp)
        except OSError:
            pass
        return E.read_fmg_names(msg, 'GoodsName.fmg')
    except Exception as e:
        print(f'  (FMG names unavailable: {e} — rendering with name="?")')
        return {}


def main():
    gts_raw = json.load(open(os.path.join(DATA, 'goods_type_sortgroup.json'), encoding='utf-8'))
    GTS = {int(k): tuple(v) for k, v in gts_raw.items()}
    icon_table = json.load(open(os.path.join(DATA, 'item_icon_table.json'), encoding='utf-8'))
    EXCEPTION_IDS = TC.load_exception_ids(icon_table)
    placed = {int(k) - 500000000 for k in icon_table if int(k) >= 500000000}
    names = load_goods_names()

    # Universe = NAMED goods only when names are available: an unnamed EquipParamGoods row is an
    # internal/placeholder entry (no display string), never a real collectible, so dropping them cuts
    # most of the param noise. (Upgrade-level variants — Flask +N, Spirit Ash +N — ARE named, so they
    # still inflate Spirits / Stat Boosts somewhat; noted in the doc caveat.)
    universe = [g for g in sorted(GTS) if (not names) or g in names]
    skipped_unnamed = len(GTS) - len(universe)

    # category -> {'known': [ids], 'placed': n, 'unplaced': [ids]}, confident categories only
    by_cat = defaultdict(lambda: {'known': [], 'placed': 0, 'unplaced': []})
    tail_known = tail_placed = 0
    for gid in universe:
        cat, confident = TC.classify(gid + 500000000, GTS, EXCEPTION_IDS)
        if not confident:
            tail_known += 1
            if gid in placed:
                tail_placed += 1
            continue
        rec = by_cat[cat]
        rec['known'].append(gid)
        if gid in placed:
            rec['placed'] += 1
        else:
            rec['unplaced'].append(gid)

    total_known = sum(len(r['known']) for r in by_cat.values())
    total_unplaced = sum(len(r['unplaced']) for r in by_cat.values())

    L = []
    L.append('# Known-but-unplaced items')
    L.append('')
    L.append('> Generated by `tools/unplaced_items.py`. Per F1 category, the goods the game HAS that '
             'classify into it but are never PLACED as a marker (universe = all EquipParamGoods rows '
             'classified by the live taxonomy; placed = `item_icon_table.json`, the ERR-bake set). '
             'A randomizer/other mod places a different set — this is the ERR baseline. Do not edit by hand.')
    L.append('')
    L.append(f'_{total_known} known (named) goods across {len(by_cat)} confident categories; '
             f'**{total_unplaced} never placed**. '
             f'(+{tail_known} catch-all/key-item-tail goods, {tail_placed} of them placed — '
             f'the uncertain surface, not itemised here.)_')
    L.append('')
    L.append(f'> Caveat: universe is NAMED goods only ({skipped_unnamed} unnamed/internal rows '
             f'dropped). Upgrade-level variants (Flask of Crimson Tears +N, Spirit Ash +N) ARE named '
             f'so they still inflate **Equipment - Spirits** and **Loot - Stat Boosts** — treat those '
             f'two counts as loose. The spell / cookbook / consumable gaps are the actionable rows.')
    L.append('')
    L.append('| category | known | placed | unplaced |')
    L.append('|---|---:|---:|---:|')
    for cat in sorted(by_cat):
        r = by_cat[cat]
        L.append(f'| {cat} | {len(r["known"])} | {r["placed"]} | {len(r["unplaced"])} |')
    L.append('')

    for cat in sorted(by_cat):
        r = by_cat[cat]
        if not r['unplaced']:
            continue
        L.append(f'## {cat} — {len(r["unplaced"])} unplaced')
        L.append('')
        L.append('| item | id |')
        L.append('|---|---|')
        for gid in r['unplaced']:
            L.append(f'| {names.get(gid, "?")} | {gid} |')
        L.append('')

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(L))
    print(f'wrote {OUT}  ({total_known} known, {total_unplaced} unplaced, {len(by_cat)} categories)')


if __name__ == '__main__':
    main()
