#pragma once
// Generated by tools/generate_overlay_icons.py. Category icon atlas for the in-game
// config overlay, embedded as a compressed PNG blob (decoded once at runtime via
// stb_image — keeps the generated file small vs a raw RGBA array). ATLAS_W/H/CELL +
// ICON_CELLS describe the decoded atlas geometry (unchanged by the PNG packing).

namespace goblin::overlay_icons
{
    extern const int ATLAS_W;
    extern const int ATLAS_H;
    extern const int CELL;
    extern const unsigned char ATLAS_PNG[]; // PNG-encoded atlas (decode to ATLAS_W*ATLAS_H RGBA)
    extern const int ATLAS_PNG_LEN;         // ATLAS_PNG byte count
    struct IconCell { const char *key; int col; int row; };
    extern const IconCell ICON_CELLS[];
    extern const int ICON_CELL_COUNT;
}
