#pragma once
// Generated by tools/generate_overlay_icons.py. Category icon atlas for
// the in-game config overlay (raw RGBA, no runtime decode).

namespace goblin::overlay_icons
{
    extern const int ATLAS_W;
    extern const int ATLAS_H;
    extern const int CELL;
    extern const unsigned char ATLAS_RGBA[]; // ATLAS_W*ATLAS_H*4, row-major
    struct IconCell { const char *key; int col; int row; };
    extern const IconCell ICON_CELLS[];
    extern const int ICON_CELL_COUNT;
    extern const int LOGO_W;
    extern const int LOGO_H;
    extern const unsigned char LOGO_RGBA[]; // LOGO_W*LOGO_H*4, row-major
}
